manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/eospj
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: mm/experiments
      import: app/west.yml
  self:
    path: config
