manifest:
  remotes:
    - name: eos
      url-base: https://github.com/eospj
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: eospj
      revision: main
      import: app/west.yml
  self:
    path: config
